field.formatter.settings.micromodal_field_formatter:
  type: field.formatter.settings.image
  label: 'Media thumbnail field display format settings'
  mapping:
    thumbnail_image_style:
      type: string
      label: 'Thumbnail Image Style'
